name: alphafold_non_docker
channels:
  - pytorch
  - conda-forge
  - defaults
  - anaconda
  - bioconda
dependencies:
  - python==3.8
  - pip==21.1.2
  - openmm==7.5.1
  - cudnn==8.2.1.32  # Change version if not compatible with current system
  - cudatoolkit==11.0.3  # Change version if not compatible with current system
  - pdbfixer==1.7
  - hmmer==3.3.2
  - hhsuite==3.3.0
  - kalign2==2.04
  - aria2==1.34.0
  - pip:
      - -r requirements.txt
      # Change version if not compatible with current system - Note that cuda111 supports CUDA 11.3
      - jax -f https://storage.googleapis.com/jax-releases/jax_releases.html
      - jaxlib==0.1.69+cuda111 -f https://storage.googleapis.com/jax-releases/jax_releases.html